power: Fix D-Bus proxy errors in test
Despite the object already having an object path associated, we
apparently need to pass it again to D-Bus calls. This fixes errors such
as:
DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface '(null)' on object at path /org/gnome/SessionManager

when calling "Inhibit" or "Uninhibit".