xsettings: Fix build error due to missing gnome-settings-bus.h include
The gsd-xsettings-manager.c code uses gnome_settings_is_wayland() which
is declared in gnome-settings-bus.h, add this to the includes.

This fixes the following build-error for me:

../plugins/xsettings/gsd-xsettings-manager.c: In function ‘gsd_xsettings_manager_start’:
../plugins/xsettings/gsd-xsettings-manager.c:1396:13: error: implicit declaration of function ‘gnome_settings_is_wayland’ [-Werror=implicit-function-declaratio]
 1396 |         if (gnome_settings_is_wayland ())
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors