build: Bump minimum GLib dependency to 2.64
It’s needed for `g_warning_once()`, as used in the media-keys plugin
since January 2023.

Debian Stable currently ships GLib 2.74, so 2.64 should be very widely
available by now.

This fixes the following compiler warnings:
```
../../source/gnome-settings-daemon/plugins/media-keys/gsd-media-keys-manager.c: In function ‘do_config_power_button_action’:
../../source/gnome-settings-daemon/plugins/media-keys/gsd-media-keys-manager.c:2047:13: error: Not available before 2.64 [-Werror]
 2047 |                 g_warning_once ("Virtual machines only honor the 'nothing' power-button-action, and will shutdown otherwise");
      |             ^   ~~~~~~~~~~~~~~~~~~~~~~~
../../source/gnome-settings-daemon/plugins/media-keys/gsd-media-keys-manager.c:2067:13: error: Not available before 2.60 [-Werror]
 2067 |                 G_GNUC_FALLTHROUGH;
      |             ^   ~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

Signed-off-by: Philip Withnall <pwithnall@gnome.org>