dummy: Fix missing dependency in some setups
/usr/bin/ld: gsd_dummy-main.o: undefined reference to symbol 'g_dbus_proxy_call'
/mnt/wd20ezrx-00dc0b0/JHBuild/3.24/install/lib/libgio-2.0.so.0: error adding symbols: DSO missing from command line

Note that the gio dependency should be dragged in via libgsd, but isn't
depending on the build flags used.

https://bugzilla.gnome.org/show_bug.cgi?id=772900